author: AVM
name: getexamples
description: Gets example directories from `examples/` and outputs them as a JSON array.
inputs:
  testSubscriptionIds:
    description: A JSON array of subscription IDs to use for testing.
    required: true
    default: '[]'

outputs:
  examples:
    description: The examples to test
    value: ${{ steps.getexamples.outputs.examples }}

runs:
  using: composite
  steps:
    - name: get examples
      id: getexamples
      run: |
        $examples = Get-ChildItem -Directory
        $processedExamples = @()

        $subscriptions = $env:TEST_SUBSCRIPTION_IDS | ConvertFrom-Json
        $hasSubscriptions = $subscriptions.Length -gt 0

        for ($i = 0; $i -lt $examples.Count; $i++) {
          if (Test-Path "$($examples[$i].FullName)/.e2eignore") {
            Write-Host "Skipping example $($examples[$i].Name) because it contains a .e2eignore file."
            continue
          }
          $subscriptionIndex = $hasSubscriptions ? ($i % $subscriptions.Length) : 0
          $processedExamples += @{
            name              = $examples[$i].Name
            subscriptionIndex = $subscriptionIndex
            subscriptionId    = $hasSubscriptions ? $subscriptions[$subscriptionIndex].id : ""
            subscriptionName  = $hasSubscriptions ? $subscriptions[$subscriptionIndex].name : ""
          }
        }

        $json = ConvertTo-Json $processedExamples -Compress
        Write-Host "examples=$json" >> $env:GITHUB_OUTPUT

      working-directory: examples
      shell: pwsh
      env:
        TEST_SUBSCRIPTION_IDS: ${{ inputs.testSubscriptionIds }}
