author: AVM
name: getexamples
description: Gets example directories from `examples/` and outputs them as a JSON array.
outputs:
  examples:
    description: The examples to test
    value: ${{ steps.getexamples.outputs.examples }}
runs:
  using: composite
  steps:
    - name: get examples
      id: getexamples
      run: |
        $examples = Get-ChildItem -Directory
        $processedExamples = @()

        $subscriptions = $env:TEST_SUBSCRIPTION_IDS | ConvertFrom-Json

        for ($i = 0; $i -lt $examples.Count; $i++) {
          $files = Get-ChildItem -Path $examples[$i].FullName -Force
          if ($files.Name -contains ".e2eignore") {
            Write-Host "Skipping example $($examples[$i].Name) because it contains a .e2eignore file."
            continue
          }
          $subscriptionIndex = ($i % $subscriptions.Length)
          $processedExamples += @{
            name = $examples[$i].Name
            subscriptionIndex = $subscriptionIndex
            subscriptionId = $subscriptions[$subscriptionIndex].id
            subscriptionName = $subscriptions[$subscriptionIndex].name
          }
        }

        $json = ConvertTo-Json $processedExamples -Compress
        Write-Host "examples=$json" >> $env:GITHUB_OUTPUT

      working-directory: examples
      shell: pwsh
      env:
        TEST_SUBSCRIPTION_IDS: ${{ secrets.TEST_SUBSCRIPTION_IDS }}
