author: AVM
name: getexamples
description: Gets example directories from `examples/` and outputs them as a JSON array.
outputs:
  examples:
    description: The examples to test
    value: ${{ steps.getexamples.outputs.examples }}
runs:
  using: composite
  steps:
    - name: get examples
      id: getexamples
      run: |
        DIRS=$(for dir in */; do
          if [ -f "$dir/.e2eignore" ]; then
            continue
          fi
          echo "$dir"
        done | \
        cut -d/ -f1 | \
        jq --raw-input --slurp --compact-output 'split("\n")[:-1]')

        echo examples="$DIRS" >> "$GITHUB_OUTPUT"
      working-directory: examples
      shell: bash
