---
name: Managed PR Check and Test Examples

on:
  workflow_call:

# These are used by nearly every step and job, so we define them here to avoid repetition.
env:
  ARM_CLIENT_ID_OVERRIDE: ${{ secrets.ARM_CLIENT_ID_OVERRIDE }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID_OVERRIDE: ${{ secrets.ARM_SUBSCRIPTION_ID_OVERRIDE }}
  ARM_TENANT_ID_OVERRIDE: ${{ secrets.ARM_TENANT_ID_OVERRIDE }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_USE_OIDC: "true"
  FORCE_COLOR: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SECRETS_CONTEXT: ${{ toJson(secrets) }}
  TF_IN_AUTOMATION: 1
  TF_VAR_enable_telemetry: "false"
  VARS_CONTEXT: ${{ toJson(vars) }}

jobs:
  subscriptions:
    name: Select Randomized Test Subscriptions
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    environment: no-approval
    outputs:
      subscriptionId: ${{ steps.subscriptions.outputs.subscriptionId }}
      subscriptionName: ${{ steps.subscriptions.outputs.subscriptionName }}
      subscriptionsJson: ${{ steps.subscriptions.outputs.subscriptionsJson }}
    steps:
      - name: Shuffle and select test subscriptions
        id: subscriptions
        run: |
          $subscriptions = $env:TEST_SUBSCRIPTION_IDS | ConvertFrom-Json
          $subscriptions = $subscriptions | Get-Random -Shuffle

          $subscriptionsJson = ConvertTo-Json $subscriptions -Compress
          Write-Host "Randomized subscriptions: $subscriptionsJson"
          Write-Output "subscriptionsJson=$($subscriptionsJson)" >> $env:GITHUB_OUTPUT

          $defaultSubscription = $subscriptions[0]
          Write-Host "Defaulting to subscription $($defaultSubscription.name) $($defaultSubscription.id) for this workflow run"
          Write-Output "subscriptionId=$($defaultSubscription.id)" >> $env:GITHUB_OUTPUT
          Write-Output "subscriptionName=$($defaultSubscription.name)" >> $env:GITHUB_OUTPUT
        env:
          TEST_SUBSCRIPTION_IDS: ${{ secrets.TEST_SUBSCRIPTION_IDS }}
        shell: pwsh

  pr-check:
    name: PR Check (Lint, Format, Validate)
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    environment: pr-check
    needs: subscriptions
    steps:
      - name: Free up runner disk space
        run: |
          sudo rm -fr /opt/hostedtoolcache
          df -h

      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d #v5.0.0

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Run AVM PR Check
        run: |
          set -e

          export ARM_SUBSCRIPTION_ID=${{ needs.subscriptions.outputs.subscriptionId }}
          echo "Using subscription ${{ needs.subscriptions.outputs.subscriptionName }} $ARM_SUBSCRIPTION_ID for PR check"

          if ! [ -z "$RUNNER_DEBUG" ]; then
            echo "PORCH_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo "AVM_PORCH_STDOUT=--stdout --success" >> $GITHUB_ENV
          fi

          export REMOTE_SCRIPT="https://raw.githubusercontent.com/Azure/avm-terraform-governance/main/scripts"
          # This needs to be in the parent directory to avoid git seeing the file as a change
          curl -H 'Cache-Control: no-cache, no-store' -sSL "$REMOTE_SCRIPT/gha-azure-cred-prep.sh" -o ../prepare-credential.sh
          source ../prepare-credential.sh

          # Fix Docker socket permissions for CI
          sudo chmod 666 /var/run/docker.sock

          ./avm pr-check

  unit-test:
    name: Terraform Unit Tests
    runs-on: ubuntu-latest
    environment: no-approval
    steps:
      - name: Free up runner disk space
        run: |
          sudo rm -fr /opt/hostedtoolcache
          df -h

      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d #v5.0.0

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Run Terraform unit tests
        run: |
          set -e

          if ! [ -z "$RUNNER_DEBUG" ]; then
            echo "PORCH_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo "AVM_PORCH_STDOUT=--stdout --success" >> $GITHUB_ENV
          fi

          # Fix Docker socket permissions for CI
          sudo chmod 666 /var/run/docker.sock

          ./avm tf-test-unit

  integration-test:
    name: Terraform Integration Tests
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    environment: pr-check
    needs: subscriptions
    steps:
      - name: Free up runner disk space
        run: |
          sudo rm -fr /opt/hostedtoolcache
          df -h

      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d #v5.0.0

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Run Terraform integration tests
        run: |
          set -e

          export ARM_SUBSCRIPTION_ID=${{ needs.subscriptions.outputs.subscriptionId }}
          echo "Using subscription ${{ needs.subscriptions.outputs.subscriptionName }} $ARM_SUBSCRIPTION_ID for Integration Tests"

          export REMOTE_SCRIPT="https://raw.githubusercontent.com/Azure/avm-terraform-governance/main/scripts"
          # This needs to be in the parent directory to avoid git seeing the file as a change
          curl -H 'Cache-Control: no-cache, no-store' -sSL "$REMOTE_SCRIPT/gha-azure-cred-prep.sh" -o ../prepare-credential.sh
          source ../prepare-credential.sh

          if ! [ -z "$RUNNER_DEBUG" ]; then
            echo "PORCH_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo "AVM_PORCH_STDOUT=--stdout --success" >> $GITHUB_ENV
          fi

          # Fix Docker socket permissions for CI
          sudo chmod 666 /var/run/docker.sock

          ./avm tf-test-integration

  getexamples:
    name: Discover Examples
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    environment: no-approval
    needs: subscriptions
    outputs:
      examples: ${{ steps.getexamples.outputs.examples }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Build example matrix and assign subscriptions
        id: getexamples
        run: |
          $examples = Get-ChildItem -Directory
          $processedExamples = @()

          $subscriptions = $env:subscriptionsJson | ConvertFrom-Json

          for ($i = 0; $i -lt $examples.Count; $i++) {
            if (Test-Path "$($examples[$i].FullName)/.e2eignore") {
              Write-Host "Skipping example $($examples[$i].Name) because it contains a .e2eignore file."
              continue
            }
            $subscriptionIndex = $i % $subscriptions.Length
            $processedExamples += @{
              name              = $examples[$i].Name
              subscriptionIndex = $subscriptionIndex
              subscriptionId    = $subscriptions[$subscriptionIndex].id
              subscriptionName  = $subscriptions[$subscriptionIndex].name
            }
          }

          $json = ConvertTo-Json $processedExamples -Compress
          Write-Output "examples=$json" >> $env:GITHUB_OUTPUT

        working-directory: examples
        shell: pwsh
        env:
          subscriptionsJson: ${{ needs.subscriptions.outputs.subscriptionsJson }}

  checksetup:
    name: Check for Global Setup Script
    runs-on: ubuntu-latest
    environment: no-approval
    outputs:
      setup_exists: ${{ steps.check-setup.outputs.setup_exists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Check if examples/setup.sh exists
        id: check-setup
        run: |
          if [ -f examples/setup.sh ]; then
            echo "setup_exists=true" >> $GITHUB_OUTPUT
          else
            echo "setup_exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

  globalsetup:
    name: Run Global Setup
    if: needs.checksetup.outputs.setup_exists == 'true' && github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    environment: examples-test
    needs: [ checksetup, subscriptions ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Run global setup script
        run: |
          set -e

          export ARM_SUBSCRIPTION_ID=${{ needs.subscriptions.outputs.subscriptionId }}
          echo "Using subscription ${{ needs.subscriptions.outputs.subscriptionName }} $ARM_SUBSCRIPTION_ID for global setup"

          export REMOTE_SCRIPT="https://raw.githubusercontent.com/Azure/avm-terraform-governance/main/scripts"
          # This needs to be in the parent directory to avoid git seeing the file as a change
          curl -H 'Cache-Control: no-cache, no-store' -sSL "$REMOTE_SCRIPT/gha-azure-cred-prep.sh" -o ../prepare-credential.sh
          source ../prepare-credential.sh

          if ! [ -z "$RUNNER_DEBUG" ]; then
            echo "PORCH_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo "AVM_PORCH_STDOUT=--stdout --success" >> $GITHUB_ENV
          fi

          ./avm global-teardown
        shell: bash

  testexamples:
    name: Test Example - ${{ matrix.name }}
    if: always() && !failure() && !cancelled() && github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    needs: [getexamples, checksetup, globalsetup]
    environment: examples-test
    strategy:
      matrix:
        include: ${{ fromJson(needs.getexamples.outputs.examples) }}
      fail-fast: false
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d #v5.0.0
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Deploy and validate example
        shell: bash
        env:
          AVM_EXAMPLE: ${{ matrix.name }}
          AVM_RUNNING_IN_GITHUB_ACTIONS: true
        run: |
          set -e

          echo "::add-mask::${{ matrix.subscriptionId }}"
          export ARM_SUBSCRIPTION_ID=${{ matrix.subscriptionId }}
          echo "Using subscription ${{ matrix.subscriptionName }} $ARM_SUBSCRIPTION_ID (index: ${{ matrix.subscriptionIndex }}) for example $AVM_EXAMPLE"

          export REMOTE_SCRIPT="https://raw.githubusercontent.com/Azure/avm-terraform-governance/main/scripts"
          # This needs to be in the parent directory to avoid git seeing the file as a change
          curl -H 'Cache-Control: no-cache, no-store' -sSL "$REMOTE_SCRIPT/gha-azure-cred-prep.sh" -o ../prepare-credential.sh
          source ../prepare-credential.sh

          if ! [ -z "$RUNNER_DEBUG" ]; then
            echo "PORCH_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo "AVM_PORCH_STDOUT=--stdout --success" >> $GITHUB_ENV
          fi

          # Fix Docker socket permissions for CI
          sudo chmod 666 /var/run/docker.sock

          ./avm test-examples

  checkteardown:
    name: Check for Global Teardown Script
    runs-on: ubuntu-latest
    if: always() && github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
    needs: testexamples
    environment: no-approval
    outputs:
      teardown_exists: ${{ steps.check-teardown.outputs.teardown_exists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Check if examples/teardown.sh exists
        id: check-teardown
        run: |
          if [ -f examples/teardown.sh ]; then
            echo "teardown_exists=true" >> $GITHUB_OUTPUT
          else
            echo "teardown_exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

  globalteardown:
    name: Run Global Teardown
    if: always() && needs.checkteardown.outputs.teardown_exists == 'true' && github.event.repository.name != 'terraform-azurerm-avm-template' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    environment: examples-test
    needs: [checkteardown, subscriptions]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Run global teardown script
        run: |
          set -e

          export ARM_SUBSCRIPTION_ID=${{ needs.subscriptions.outputs.subscriptionId }}
          echo "Using subscription ${{ needs.subscriptions.outputs.subscriptionName }} $ARM_SUBSCRIPTION_ID for global teardown"

          export REMOTE_SCRIPT="https://raw.githubusercontent.com/Azure/avm-terraform-governance/main/scripts"
          # This needs to be in the parent directory to avoid git seeing the file as a change
          curl -H 'Cache-Control: no-cache, no-store' -sSL "$REMOTE_SCRIPT/gha-azure-cred-prep.sh" -o ../prepare-credential.sh
          source ../prepare-credential.sh

          if ! [ -z "$RUNNER_DEBUG" ]; then
            echo "PORCH_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
            echo "AVM_PORCH_STDOUT=--stdout --success" >> $GITHUB_ENV
          fi

          ./avm global-teardown
        id: global-teardown
        shell: bash
