---
name: repository config - test

on:
  pull_request:
    paths:
      - .github/workflows/repository-config-test.yml
      - tf-repo-mgmt/repository-config/config.json
      - tf-repo-mgmt/scripts/lib/AvmPreCommit.ps1
      - tf-repo-mgmt/scripts/lib/RepositoryConfig.ps1
      - tf-repo-mgmt/scripts/Test-AvmPreCommit.ps1
      - tf-repo-mgmt/scripts/Test-RepositoryConfig.ps1
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test repository configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test repository configuration
        shell: pwsh
        run: |
          ./tf-repo-mgmt/scripts/Test-RepositoryConfig.ps1
          ./tf-repo-mgmt/scripts/Test-AvmPreCommit.ps1
