---
name: Repository Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./tf-repo-mgmt

jobs:
  repository-data:
    name: Get Repository Data
    runs-on: ubuntu-latest
    environment: avm

    steps:
      - name: Checkout Bootstrap Modules
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.AVM_APP_CLIENT_ID }}
          private-key: ${{ secrets.AVM_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get Repository Data
        run: |
          $repositories = @(../.github/actions/avm-repos/scripts/Get-RepositoriesWhereAppInstalled.ps1 -outputDirectory "${{ github.workspace }}" -metaDataFilePath "${{ github.workspace }}/tf-repo-mgmt/repository-meta-data/meta-data.csv")
          Write-Host (ConvertTo-Json $repositories -Depth 10)

          # remove the terraform-azurerm-avm-template repo from the list
          $repositories = $repositories.Where({ $_.repoName -ne 'terraform-azurerm-avm-template' })

          ./scripts/Invoke-RepositoryDataSync.ps1 -repositories $repositories -outputDirectory "${{ github.workspace }}"

        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Upload Repo Data JSON
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: repositoryData.json
          path: repositoryData.json

      - name: Upload Repo Data CSV Files
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: CSV
          path: |
            *.csv

      - name: Upload Repo Logs Json
        if: always() && hashFiles('issues.log.json') != ''
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: issues.log.json
          path: issues.log.json

      - name: Repo Error
        if: always() && hashFiles('issues.log.json') != ''
        run: |
          $issueLogJson = Get-Content -Path "${{ github.workspace }}/issues.log.json" -Raw
          $issueLog = ConvertFrom-Json $issueLogJson
          $issueLog | Where-Object { $_.severity -eq "error" } | ForEach-Object {
            echo "::error title=$($_.repoId) has issues::$($_.message)"
          }
          $issueLog | Where-Object { $_.severity -eq "warning" } | ForEach-Object {
            echo "::warning title=$($_.repoId) has issues::$($_.message)"
          }
        shell: pwsh
